name: Test Foster Dashboard

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd FosterDash
        pip install -r requirements_foster_dashboard.txt
    
    - name: Test imports
      run: |
        cd FosterDash
        python -c "import streamlit, pandas, numpy, supabase; print('All imports successful')"
    
    - name: Test dashboard startup
      run: |
        cd FosterDash
        timeout 30s streamlit run foster_dashboard.py --server.headless true --server.port 8501 || true
